export const cidades = [
  {value: "AC", nome: "Acre"},
  {value: "AL", nome: "Alagoas"},
  {value: "AP", nome: "Amapá"},
  {value: "AM", nome: "Amazonas"},
  {value: "BA", nome: "Bahia"},
  {value: "CE", nome: "Ceará"},
  {value: "DF", nome: "Distrito Federal"},
  {value: "ES", nome: "Espirito Santo"},
  {value: "GO", nome: "Goiás"},
  {value: "MA", nome: "Maranhão"},
  {value: "MS", nome: "Mato Grosso do Sul"},
  {value: "MT", nome: "Mato Grosso"},
  {value: "MG", nome: "Minas Gerais"},
  {value: "PA", nome: "Pará"},
  {value: "PB", nome: "Paraíba"},
  {value: "PR", nome: "Paraná"},
  {value: "PE", nome: "Pernambuco"},
  {value: "PI", nome: "Piauí"},
  {value: "RJ", nome: "Rio de Janeiro"},
  {value: "RN", nome: "Rio Grande do Norte"},
  {value: "RS", nome: "Rio Grande do Sul"},
  {value: "RO", nome: "Rondônia"},
  {value: "RR", nome: "Roraima"},
  {value: "SC", nome: "Santa Catarina"},
  {value: "SP", nome: "São Paulo"},
  {value: "SE", nome: "Sergipe"},
  {value: "TO", nome: "Tocantins"},
]